spring:
  datasource:
    url: jdbc:postgresql://localhost:54311/aoalocaldb
    username: postgres
    password: JRaspberry1!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: aoalocal
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
      registration:
        provider:
          coocon-auth:
            authorization-uri: https://localhost:8080/oauth/authorize
            token-uri: https://localhost:8080/oauth/token
            user-info-uri: https://localhost:8080/v2/user/me
            user-name-attribute: id
logging:
  level:
    com: debug
