server:
  port: 8180
spring:
  datasource:
    url: jdbc:postgresql://localhost:54311/aoalocaldb
    username: postgres
    password: JRaspberry1!
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: aoalocal
        format_sql: true
        show_sql: true
  security:
    debug: true
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
          coocon:
            client-id: coocon-client-id
            client-secret: coocon-client-secret

        provider:
          coocon:
            authorization-uri: http://localhost:8180/oauth/authorize
            token-uri: http://localhost:8180/oauth/token
            user-info-uri: http://localhost:8180/v2/user/me
            user-name-attribute: id
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/jwt/issuer
          jwk-set-uri: https://idp.example.com/oauth2/jwks # (2)
          public-key-location: classpath:public.pem # (3)
logging:
  level:
    com: debug
